### PR TITLE
Revert "Remove from M&P the room data of Final Level/Lab/Overworld/Tower"

### PR DESCRIPTION
**Pull request by leo60228**
Reverts TerryCavanagh/VVVVVV#124

This segfaults on many platforms, due to `fillcontents` dereferencing an uninitialized pointer. See https://github.com/NixOS/nixpkgs/pull/79068#issuecomment-583738049.

```
Starting program: /nix/store/24g187p6zjgawsgcss05rdq7nbirj8z6-vvvvvv-bin-unstable-2020-02-02/bin/VVVVVV -assets /nix/store/30jgxphl7vl4iwvsxcs5yv28z6868rwm-mapdata.zip
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/nix/store/6yaj6n8l925xxfbcd65gzqx3dz7idrnn-glibc-2.27/lib/libthread_db.so.1".
[New Thread 0x7ffff68fb700 (LWP 29967)]
[New Thread 0x7fffe6516700 (LWP 29968)]

Thread 1 "VVVVVV" received signal SIGSEGV, Segmentation fault.
std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::basic_stringbuf (__mode=24, __str=<error reading variable: Cannot access memory at address 0x8>, this=0x7fffffff7098)
    at /nix/store/qksib0d7ygx1mmqk7172yjz02ya13lsh-gcc-9.2.0/include/c++/9.2.0/sstream:127
127             _M_string(__str.data(), __str.size(), __str.get_allocator())
(gdb) bt
#0  std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::basic_stringbuf (__mode=24, __str=<error reading variable: Cannot access memory at address 0x8>, this=0x7fffffff7098)
    at /nix/store/qksib0d7ygx1mmqk7172yjz02ya13lsh-gcc-9.2.0/include/c++/9.2.0/sstream:127
#1  std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream (__m=24, __str=<error reading variable: Cannot access memory at address 0x8>, this=0x7fffffff7080, __in_chrg=<optimized out>,
    __vtt_parm=<optimized out>) at /nix/store/qksib0d7ygx1mmqk7172yjz02ya13lsh-gcc-9.2.0/include/c++/9.2.0/sstream:774
#2  split (s=<error reading variable: Cannot access memory at address 0x8>, delim=delim@entry=44 ',', elems=std::vector of length 0, capacity 0) at ../src/UtilityClass.cpp:68
#3  0x0000000000581aef in split (s=..., delim=delim@entry=44 ',') at ../src/UtilityClass.cpp:80
#4  0x000000000057c558 in towerclass::fillcontents (this=this@entry=0x5f1a90 <map+1616>, tmap=std::vector of length 0, capacity 0) at /nix/store/qksib0d7ygx1mmqk7172yjz02ya13lsh-gcc-9.2.0/include/c++/9.2.0/bits/stl_vector.h:1040
#5  0x000000000057c6f4 in towerclass::loadmap (this=this@entry=0x5f1a90 <map+1616>) at ../src/Tower.cpp:1199
#6  0x000000000057f634 in towerclass::towerclass (this=0x5f1a90 <map+1616>) at ../src/Tower.cpp:33
#7  0x000000000049c0f1 in mapclass::mapclass (this=0x5f1440 <map>) at /nix/store/qksib0d7ygx1mmqk7172yjz02ya13lsh-gcc-9.2.0/include/c++/9.2.0/bits/char_traits.h:300
#8  0x0000000000582c8a in __static_initialization_and_destruction_0 (__initialize_p=__initialize_p@entry=1, __priority=__priority@entry=65535)
    at /nix/store/qksib0d7ygx1mmqk7172yjz02ya13lsh-gcc-9.2.0/include/c++/9.2.0/bits/stl_vector.h:94
#9  0x00000000005842f6 in _GLOBAL__sub_I_main.cpp(void) () at ../src/main.cpp:570
#10 0x00000000005a3f4d in __libc_csu_init ()
#11 0x00007ffff76ffb1d in __libc_start_main () from /nix/store/aag9d1y4wcddzzrpfmfp9lcmc7skd7jk-glibc-2.27/lib/libc.so.6
#12 0x000000000041ac5a in _start () at ../sysdeps/x86_64/start.S:120
```

### CODE REVIEW

**Comment by flibitijibibo** [comment]
Guess this explains why I left it alone. @InfoTeddy, is this quick to fix or should I revert until it can be redone?

**Comment by InfoTeddy** [comment]
Seems like what instead should happen is `loadlevel()` for all of them, plus `Tower.cpp`'s `loadmap()`, `loadminitower1()`, and `loadminitower2()` all should initialize a bunch of 0s when compiled with `MAKEANDPLAY`. Something like:

```c++
for (int j = 0; j < 30; j++)
{
    tmap.push_back("0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0");
}
```

But for the Tower, change 30 to 700, and for the minitowers change it to 100.

Reverting the removals for Final Level/Lab/Overworld/Tower still leaves the fact that Space Station 1 & 2 and Warp Zone are still removed. Who's to say that *those* won't segfault on any platforms, too?

**Comment by flibitijibibo** [comment]
The stub map sounds a lot better - if someone can try it out I can merge that instead.

**Comment by InfoTeddy** [comment]
Alright, I opened #155 to fix this.

**Comment by flibitijibibo** [comment]
Closed by 155.

**Pull request closed without merging**
