### PR TITLE
Fix unwinnable save from rescuing Violet out of order

### PR DESCRIPTION
**Pull request by InfoTeddy**
You're intended to rescue Violet first, and not second, third, or fourth, and especially not last.

If you rescue her second, third, or fourth, your crewmate progress will be reset, but you won't be able to re-rescue them again. This is because Vitellary, Verdigris, Victoria, and Vermilion will be temporarily marked as rescued during the `bigopenworld` cutscene, so duplicate versions of them don't spawn during the cutscene, and then will be marked as missing later to undo it.

This first issue can be trivially fixed by simply toggling flags to prevent duplicates of them from spawning during the cutscene instead of fiddling with their rescue statuses.

However, there is still another issue. If you rescue Violet last, then you won't be warped to the Final Level, meaning you can't properly complete the game. This can be fixed by adding a `crewrescued() == 6` check to the Space Station 1 Level Complete cutscene. There is additionally a temporary unrescuing of Violet so she doesn't get duplicated during the `bigopenworld` cutscene, and I've had to move that to the start of the `bigopenworld` and `bigopenworldskip` scripts, otherwise the `crewrescued() == 6` check won't work properly.

I haven't added hooks for Intermission 1 or 2 because you're not really meant to play the intermissions with Violet (but you probably could anyway, there'd just be no dialogue).

Oh, and the pre-Final Level cutscene expects the player to already be hidden before it starts playing, but if you rescue Violet last the player is still visible, so I've fixed that. But there still ends up being two Violets, so I'll probably replace it with a special cutscene later that's not so nonsensical.

## Legal Stuff:

By submitting this pull request, I confirm that...

- [X] My changes may be used in a future commercial release of VVVVVV (for
  example, a 2.3 update on Steam for Windows/macOS/Linux)
- [X] I will be credited in a `CONTRIBUTORS` file and the "GitHub Friends"
  section of the credits for all of said releases, but will NOT be compensated
  for these changes

### CODE REVIEW

**Comment by Nikostormkilla** [comment]
By the way, the easiest way and only way to rescue Violet second or just not first is to hold R during the opening cutscene as you'll spawn in the ship instead of the space station

**Comment by InfoTeddy** [comment]
The *only* way? That's not true. You could use invincibility mode and go through the left exit of Exhaust Chute, then either rescue Vitellary or exit through the entrance of Space Station 2 to go to other zones.

**Comment by tzann** [comment]
I would recommend not adding hooks for Intermission 1 and 2 because that would significantly change how speedruns are done.

**Comment by InfoTeddy** [comment]
Yes, that too. That's another reason I won't be adding those hooks.

**Comment by flibitijibibo** [comment]
Checking on this real quick - are there any remaining concerns with this fix that haven't been addressed yet?

**Comment by InfoTeddy** [comment]
Pretty sure there aren't. Except for being able to have two Violets in a cutscene, but that can be a separate fix and isn't as critical as this one.

**Comment by flibitijibibo** [comment]
Cool, just wanted to be sure - the script changes make sense to me, but you never know with continuity errors like these...

**Pull request merged**
