### PR TITLE
Freebsd fix

### PR DESCRIPTION
**Pull request by evadot**
## The Basics

Thanks for making a pull request! Before making a pull request, we have some
things for you to read through first:

- We generally do not accept patches for formatting fixes, unless the formatting
  fixes are part of a functional patch (for example, when fixing a bug in a
  function you can fix up the lines surrounding it if needed).
- Patches that break compatibility with the original game data or save data will
  not be accepted.
- New features and user interface changes will most likely not be accepted
  unless they are for improving user accessibility.
- New platforms are acceptable if they use SDL + PhysicsFS and don't mess with
  the game source too much.
    - (No homebrew console targets, sorry! Maybe do the work in SDL instead?)
- Pull requests that do not fill out the Legal Stuff will be closed
  automatically.

If you understand these notes, you can delete the text in this section. Pull
requests that still have this text will be closed automatically.

## Legal Stuff:

By submitting this pull request, I confirm that...

- [X] My changes may be used in a future commercial release of VVVVVV (for
  example, a 2.3 update on Steam for Windows/macOS/Linux)
- [X] I will be credited in a `CONTRIBUTORS` file for all of said releases, but
  will NOT be compensated for these changes

## Changes:

Fix compilation on FreeBSD.

### CODE REVIEW

**Comment by flibitijibibo** [comment]
LGTM! Add yourself to `desktop_version/CONTRIBUTORS.txt` and I'll merge this in.

**Comment by evadot** [comment]
> LGTM! Add yourself to `desktop_version/CONTRIBUTORS.txt` and I'll merge this in.

Done.

**Comment by flibitijibibo** [comment]
Perfect, thanks!

**Comment by TerryCavanagh** [comment]
Thank you Evadot!

**Comment by evadot** [comment]
Thanks for the quick merge, it's awesome to be able to play this game again without booting my windows laptop :)

**Comment by benwiley4000** [comment]
@evadot what's the significance of skipping the network init only on freebsd? Surely the game doesn't require Steam to run on other systems?

**Comment by flibitijibibo** [comment]
Truthfully, it's not really necessary, but it's a sane enough microoptimization to skip loading Steamworks for systems that never had it to begin with.

**Comment by benwiley4000** [comment]
I had assumed the line was added because it was causing a compilation or runtime error. Otherwise, although perhaps saving a few cycles of time, it would mostly serve to preclude the game from ever working on FreeBSD even should a version of Steam be released for that platform. Unlikely I know.. haha.

**Comment by evadot** [comment]
> I had assumed the line was added because it was causing a compilation or runtime error. Otherwise, although perhaps saving a few cycles of time, it would mostly serve to preclude the game from ever working on FreeBSD even should a version of Steam be released for that platform. Unlikely I know.. haha.

Yes it's just easier to skip everything as we will never have steam support on FreeBSD.

**Pull request merged**
