### PR TITLE
iOS port (for desktop_version)

### PR DESCRIPTION
**Pull request by leo60228**
## Changes:

An iOS port of the C++ version to go with the Android port in #1004. The same caveats as that PR apply. An Xcode project for the ARM64 simulator can be created with a command like the following:

```
cmake .. -GXcode -DCMAKE_SYSTEM_NAME=iOS -DSDL2_FRAMEWORK=$HOME/SDL2-2.28.5/Xcode/SDL/Products/SDL2.xcframework/ios-arm64_x86_64-simulator/SDL2.framework -DCMAKE_OSX_SYSROOT=iphonesimulator -DCMAKE_OSX_ARCHITECTURES=arm64 -DDATA_ZIP=$HOME/Downloads/data.zip
```

Similar commands should work for the x86_64 simulator and real hardware, though I haven't tested the former yet. Some further changes will likely be required to properly support app signing, though I think the details of that might differ between free and paid developer accounts? To force Xcode to build for real hardware without signing, you can use this command:

```
xcodebuild -verbose -project VVVVVV.xcodeproj -configuration Release -target VVVVVV archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
```

A tvOS port would likely be fairly easy (and could potentially capitalize on a market for platformers playable with the Siri Remote?), but the only non-hacky way to store save data on tvOS is via Game Center, which requires a paid developer account.

## Legal Stuff:

By submitting this pull request, I confirm that...

- [x] My changes may be used in a future commercial release of VVVVVV
- [x] I will be credited in a `CONTRIBUTORS` file and the "GitHub Friends"
  section of the credits for all of said releases, but will NOT be compensated
  for these changes unless there is a prior written agreement

### CODE REVIEW

**Review by flibitijibibo — APPROVED** [review]
This lgtm - as soon as we're done with 2.4 stuff this should be merged in.

**Comment by leo60228** [comment]
Here's an IPA for testing: https://drive.google.com/file/d/1Szx9lOgHgcL2rb-uQlZFOE7g9BBjJ_vA/view?usp=sharing

Apple doesn't want you to be able to install an IPA directly, but you can use a tool like AltServer or TrollStore to do so.

**Comment by InfoTeddy** [comment]
This still okay? I want to merge as soon as possible :stuck_out_tongue:

Would also be nice to get an updated IPA for testing on a real iOS device.

**Comment by InfoTeddy** [comment]
Btw this needs to be updated to account for #1174.

**Comment by leo60228** [comment]
Waiting for my iPhone to charge to test on hardware, but a simulator build seems to work: https://drive.google.com/file/d/1kuCdl2CrVHs9H7_7frJzyOWG2r7VRhv2/view

**Comment by leo60228** [comment]
Android CI failure appears to be unrelated to this PR.

**Comment by leo60228** [comment]
Works on hardware, tested with a DualShock 4.

**Pull request merged**
