### PR TITLE
Add Github action to upload complete tarball

### PR DESCRIPTION
**Pull request by i0ntempest**
## Changes:
Nothing changed in the game itself. This new workflow creates a complete tarball upon every release.
*shameless (almost) copy from pytorch repo workflow*
Closes: https://github.com/TerryCavanagh/VVVVVV/issues/1111

## Legal Stuff:

By submitting this pull request, I confirm that...

- [x] My changes may be used in a future commercial release of VVVVVV
- [x] I will be credited in a `CONTRIBUTORS` file and the "GitHub Friends"
  section of the credits for all of said releases, but will NOT be compensated
  for these changes

### CODE REVIEW

**Comment by flibitijibibo** [comment]
I think this depends on a specific setup for releases; what I can do is copy over the process I do for [FNA releases](https://github.com/FNA-XNA/FNA/releases) which recursively grabs submodules and trims all the git dotfiles.

Sorry for the runaround, expect an archive of 2.4 later this weekend. I'll update the linked issue accordingly!

**Comment by i0ntempest** [comment]
Thanks, just confirming this will be done (automatically?) for future releases as well?

**Comment by flibitijibibo** [comment]
Probably not automatically, but I have scripts for this that I can copy over from my other projects that'll make it super quick.

**Comment by i0ntempest** [comment]
Sure. Still think an automatic workflow would be easier but I’m happy as long as full tarballs are provided.

**Comment by flibitijibibo** [comment]
Release has been updated with VVVVVV-2.4.zip, which contains all the submodules with the quirks included.

**Pull request closed without merging**
