### PR TITLE
Fallback to loading music from loose files if vvvvvvmusic.vvv is invalid or missing

### PR DESCRIPTION
**Pull request by leo60228**
## Changes:

Files are loaded from paths like `/home/leo60228/.local/share/VVVVVV/music/6presentingvvvvvv.ogg`. This allows the game to have less than 20MB of peak heap usage (though still ~100MB of non-heap RAM usage, which I'm investigating).

## Legal Stuff:

By submitting this pull request, I confirm that...

- [x] My changes may be used in a future commercial release of VVVVVV (for
  example, a 2.3 update on Steam for Windows/macOS/Linux)
- [x] I will be credited in a `CONTRIBUTORS` file and the "GitHub Friends"
  section of the credits for all of said releases, but will NOT be compensated
  for these changes

### CODE REVIEW

**Review by InfoTeddy — APPROVED** [review]
If @flibitijibibo is fine with the RWops stuff, then this is good to go after a rebase.

**Comment by flibitijibibo** [comment]
Makes sense to me - the only thing that seemed interesting was the way it was added to CMake, but then I remembered that SDL complicates it enough to where it wouldn't be easy to add to the physfs blob, so this is good enough.

**Comment by leo60228** [comment]
Rebased. I can't test at the moment but it compiles fine.

**Comment by leo60228** [comment]
stdout is as expected for both vvvvvvmusic.vvv and loose files, which doesn't necessarily mean anything but is a good sign.

**Comment by leo60228** [comment]
Tested and working.

**Pull request merged**
