### PR TITLE
Fix build on DragonFlyBSD

### PR DESCRIPTION
**Pull request by daftaupe**
## Changes:

More or less the same as what had to be done for FreeBSD (#11) / OpenBSD (#34), just fix the build for DragonFlyBSD.

## Legal Stuff:

By submitting this pull request, I confirm that...

- [x] My changes may be used in a future commercial release of VVVVVV (for
  example, a 2.3 update on Steam for Windows/macOS/Linux)
- [x] I will be credited in a `CONTRIBUTORS` file for all of said releases, but
  will NOT be compensated for these changes

### CODE REVIEW

**Comment by flibitijibibo** [comment]
Totally missed this, sorry! I think GitHub’s flakiness this week has caused some emails to get dropped.

**Comment by daftaupe** [comment]
> Totally missed this, sorry! I think GitHub’s flakiness this week has caused some emails to get dropped.

There was no hurry at all :)

**Comment by InfoTeddy** [comment]
You forgot to add yourself to the `githubfriends` credits list :p

**Comment by flibitijibibo** [comment]
I should probably update the template for that...

**Comment by daftaupe** [comment]
@InfoTeddy I've added myself to the CONTRIBUTORS.txt file, but I have no idea what's the githubfriends list.

**Comment by flibitijibibo** [comment]
We'll do a sync of those two lists when we do another release - as long as it's _somewhere_ in the repo it'll be fixed up for an eventual tag.

**Pull request merged**
