### PR TITLE
Update lodepng and utfcpp

### PR DESCRIPTION
**Pull request by AlexApps99**
## Changes:

Updated `lodepng` and `utfcpp`

## Legal Stuff:

By submitting this pull request, I confirm that...

- [x] My changes may be used in a future commercial release of VVVVVV (for
  example, a 2.3 update on Steam for Windows/macOS/Linux)
- [x] I will be credited in a `CONTRIBUTORS` file for all of said releases, but
  will NOT be compensated for these changes

### CODE REVIEW

**Comment by InfoTeddy** [comment]
Hm, why doesn't the game use libpng, or better yet SDL_image, instead of lodepng?

**Comment by InfoTeddy** [comment]
Also, no TinyXML update? Or is there none?

**Comment by AlexApps99** [comment]
That is a good point you raise, should I create a PR to use `SDL_image` instead?

**Comment by AlexApps99** [comment]
The other dependencies were up-to-date

**Comment by InfoTeddy** [comment]
> That is a good point you raise, should I create a PR to use `SDL_image` instead?

If you're up for it, yes.

**Comment by InfoTeddy** [comment]
> The other dependencies were up-to-date

That's what I figured.

**Comment by flibitijibibo** [comment]
I specifically removed SDL_image and replaced it with lodepng, so don’t worry about that part. Can also confirm tinyxml can’t really be touched for reasons I never figured out.

This is fine for now, but for future reference we probably won’t update dependencies until an official VVV update is coming up or a security vulnerability is exposed.

**Comment by InfoTeddy** [comment]
> I specifically removed SDL_image and replaced it with lodepng

Why did you do that, then? It's a big headscratcher for anyone not familiar with the decision.

**Comment by flibitijibibo** [comment]
One less DLL.

**Comment by AlexApps99** [comment]
Can't it be statically linked?

**Comment by AlexApps99** [comment]
Besides, AFAIK Steam provides DLLs for SDL2 so in most cases they wouldn't be needed

**Comment by InfoTeddy** [comment]
Well, yes, SDL2 DLLs are in the Steam runtime, however there are plenty of non-Steam versions of the game such as Make & Play, where we would have to distribute DLLs anyway. I still agree though, can't it be statically linked?

**Comment by flibitijibibo** [comment]
The base library could be, but then you’re also pulling in libpng and zlib as well. Point being, one is a single file with no configuration setup, the other is 3+ DLLs with autoconf and separate VS projects.

**Pull request merged**
