### PR TITLE
Re-add the font outline from the Flash and mobile versions

### PR DESCRIPTION
**Pull request by InfoTeddy**
## Legal Stuff:

By submitting this pull request, I confirm that...

- [x] My changes may be used in a future commercial release of VVVVVV (for
  example, a 2.3 update on Steam for Windows/macOS/Linux)
- [x] I will be credited in a `CONTRIBUTORS` file for all of said releases, but
  will NOT be compensated for these changes

## Changes:

* **Re-add the font outline from the Flash and mobile versions of the game**

  This uncomments the code for the font outline. Now, you will see the font outline on text that had it in the Flash version, most notably "- Press ENTER to Teleport -" and the time trial overlay text.

  This also fixes a problem with the commented code, where un-centered text didn't outline properly.

### CODE REVIEW

**Comment by flibitijibibo** [comment]
There might be a historical reason for why this was disabled... @terrycanavagh, any ideas?

**Comment by InfoTeddy** [comment]
Does editing in a ping actually ping the person involved? I know Discord doesn't ping someone if you edit in a ping, and will not remove a ping if you edit out a ping...

Just in case, @TerryCavanagh

**Comment by TerryCavanagh** [comment]
It’s been a very long time, and I no longer fully remember why I removed the font outlines in the c++ build - but I suspect I did it intentionally because I didn’t like the inconsistent look of the outlined text.

But I dunno, it’s been 9 years, I can take a fresh look. Do you have a before/after in context?

**Comment by InfoTeddy** [comment]
Before:
font_outline_before

After:
font_outline_after

For what it's worth, the mobile version still has the font outline, and they have the same look as they do here.

**Comment by FredrIQ** [comment]
It could always be made a graphics option, but that might be overkill.

**Comment by TerryCavanagh** [comment]
Thanks for going to the trouble of getting both screenshots!

I'm a little conflicted about this, but the outline looks fine in context, and if it's in the mobile version anyway then I don't see the harm in making the changed. Merging!

**Comment by flibitijibibo** [comment]
I like @FredrIQ’s idea of making it an option - if not accessibility I’d be up for having it in graphics too.

**Comment by flibitijibibo** [comment]
Toggle has been pushed: https://github.com/TerryCavanagh/VVVVVV/commit/6e9712f113388af4e3711773555e55c8620102b1

**Pull request merged**
