### PR TITLE
Call fsync on Emscripten

### PR DESCRIPTION
**Pull request by leo60228**
## Changes:

This is necessary to allow pages consuming VVVVVV.js to persist save data. See commit messages for further details.

## Legal Stuff:

By submitting this pull request, I confirm that...

- [x] My changes may be used in a future commercial release of VVVVVV
- [x] I will be credited in a `CONTRIBUTORS` file and the "GitHub Friends"
  section of the credits for all of said releases, but will NOT be compensated
  for these changes

### CODE REVIEW

**Comment by flibitijibibo** [comment]
Do we want to treat this as a PhysFS issue? The code gets pretty specific, but at the same time this looks _exactly_ like another platform's commit system, so maybe send this PR to the PhysFS issue tracker and see what Ryan thinks.

**Comment by leo60228** [comment]
That could make sense, but in my opinion the optimization to prevent all code using PhysFS from being affected by asyncify is important, and PhysFS can't really do that without knowledge of the host program that it doesn't have.

**Comment by flibitijibibo** [comment]
That makes sense to me - on the other platform we added an extension where you just call `CommitChanges()` and it effectively does what's done here; you call it after making all the filesystem updates you expect to make and the async work is done internally.

**Comment by leo60228** [comment]
That's fair. For what it's worth, if my wild guess as to the platform you're referring to is correct, I'm pretty sure that the OS isn't smart enough to process multiple filesystem calls in parallel (but I could be misremembering).

**Comment by leo60228** [comment]
Ugh, I misread the PhysFS code. It automatically flushes when calling `PHYSFS_close`. That makes things a *bit* trickier, but I think I can still work around that.

**Comment by leo60228** [comment]
The more I look at this, the less I think that it can be easily handled. Asyncify doesn't have any way to handle functions that may or may not be async (like `PHYSFS_close`), so there's no real way to restrict what asyncify applies to. Because of this, I'll close this PR and let consumers add `-s ASYNCIFY` to CFLAGS if they need persistence.

**Pull request closed without merging**
