### PR TITLE
Fix some mistakes in the pt_BR translation

### PR DESCRIPTION
**Pull request by Space-G**
## Changes:

Solves #1064 

List of changes:

| Original Name | Current translation | Suggested translation | Reasoning |
| --------------|-------------------|----------------------| --- |
| Gantry and Dolly | Pórtico e Dolly | Grua e Vagão | Aesthetics, and personally less confusing but this one is abstract |
| V Stitch | Ponto V | Costura V | Keeps the meaning, reduces ambiguity. Avoids confusion with "G Spot" (Evita assimilação a "Ponto G" mantendo o significado) |
| The Tomb of Mad Carew | A tumba de Mad carew | A tumba de Mad Carew | Capitalization (Capitalização) |
| Shockwave Rider | Cavaleiro Shockwave | Shockwave Rider | Keeps the reference to the book that wasn't released in portuguese (Mantém a referência ao livro de título Shockwave Rider) |
| On the [VW]aterfront | À [bv]eira-mar | Sindicato de [LV]adrões | Keeps the reference to the movie, using it's released title here (Mantém a referência ao filme On the Waterfront) |
| The Voon Show | O show de voons | The Voon Show | Keeps the reference to the british radio show (Mantém referência ao show humorístico de rádio The Voon Show) |
| The 9 O'Clock News | Notícias das 9 horas | Jornal das 9 | "Jornal" instead of "notícias" because that's how we call the program that shows the news on TVs and Radios. It's also what "newspaper" is called. The omission of the word "horas" (hours) is due to how we refer to programs in radios and television. (O jornal é autoexplicativo, a omissão da palavra "horas" reflete o jeito comum de falar sobre programas de televisão.) |
| Panic Room | Sala de Pânico | O quarto do pânico | Keeps the reference to the 2002 movie, using it's released pt-br name (Mantém a referência ao filme Panic Room, cujo nome em pt-br é O quarto do pânico) |
| Cosmic Creepers | Trepadeiras cósmicas | Crepúsculo Cósmico | Is the name of the cat in the brazillian dubbed version of Bedknobs and Broomsticks, keeping the original reference. (É o gato da bruxa aprendiz Eglantine Price, no filme Se a minha Cama Voasse, dublado em pt-br.) |
| The Sensible Room | A sala sensível | A sala sensata | It's a false cognate*  |
| Brass sent us under the top | Bronze nos enviou abaixo do topo |  O alto comando nos enviou | Translates "Brass" as the metal, instead of the military slang* |
| Vertigo | Vertigem | Um Corpo que Cai | Vertigo translates correctly, but the movie had a different title in PT-BR* |

\* noted by [@zaratustra on Cohost](https://cohost.org/terrycavanagh/post/3679724-vvvvvv-localisation#comment-83e4547c-5c31-4d1f-8a4e-9177eddeae30)

## Legal Stuff:

By submitting this pull request, I confirm that...

- [X] My changes may be used in a future commercial release of VVVVVV
- [X] I will be credited in a `CONTRIBUTORS` file and the "GitHub Friends"
  section of the credits for all of said releases, but will NOT be compensated
  for these changes

### CODE REVIEW

**Comment by InfoTeddy** [comment]
Would you like to be added to the credits for pt_BR translation?

**Comment by Space-G** [comment]
> Would you like to be added to the credits for pt_BR translation?

Yes, please, that would be an honour, thank you so much! 

3 translations were actually suggested by [zaratruza on Cohost](https://cohost.org/terrycavanagh/post/3679724-vvvvvv-localisation#comment-83e4547c-5c31-4d1f-8a4e-9177eddeae30), they might want to be credited aswell, maybe.

**Comment by TerryCavanagh** [comment]
Sorry, we'll put for this sort of contribution in the github contributors section! The main translation credits are for the localisation teams themselves. (We hadn't discussed this internally, so apologies for the confusion)

**Comment by TerryCavanagh** [comment]
(and thank you for the pull request!)

**Pull request merged**
