### PR TITLE
Initialize level data with 0s in M&P

### PR DESCRIPTION
**Pull request by InfoTeddy**
## Changes:

* **Initialize level data with 0s in Make & Play edition**

  Following discussion on #153, I suggested that instead of reverting my M&P guards from #124 (which would only revert it for The Final Level, The Lab, Overworld, and The Tower, leaving Space Station 1 & 2 and The Warp Zone alone which could potentially cause the same problem that motivated #153), we should initialize the map data with 0s instead.

## Legal Stuff:

By submitting this pull request, I confirm that...

- [X] My changes may be used in a future commercial release of VVVVVV (for
  example, a 2.3 update on Steam for Windows/macOS/Linux)
- [X] I will be credited in a `CONTRIBUTORS` file for all of said releases, but
  will NOT be compensated for these changes

### CODE REVIEW

**Comment by flibitijibibo** [comment]
@leo60228, can you verify this patch? If it works for you we’ll go with this as the fix.

**Comment by leo60228** [comment]
i will never get to sleep tonight

**Comment by leo60228** [comment]
It does fix the segfault, yes.

**Comment by flibitijibibo** [comment]
Cool, thanks to both of you for checking this out.

**Pull request merged**
